name: Deploy Telegram Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: main.yml
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install some-extra-library

    - name: Run Telegram Bot
      env:
        TELEGRAM_TOKEN: ${{ secrets.7936896770:AAEMsvebKzKyPJ1Z7c1Nw4prsNTYZ6E5Tu0 }}
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        python my_bot.py
